[package]
name = "chkpwned"
version = "0.1.0"
authors = ["mrobakowski <mikolaj.rob@gmail.com>"]
license = "MIT"

[dependencies]
quicli = "0.2"
indicatif = "0.9.0"
rpassword = "2.0.0"
sha1 = { version = "0.6.0", features = ["std"] }
memmap = "0.6.2"
static_assertions = "0.2.5"